name: generate breakout

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: generate breakout svgs
        uses: cyprieng/github-breakout@v1
        with:
          github_username: ${{ github.repository_owner }}

      - name: push breakout svgs to the output-breakout branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output-breakout
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
